@startuml model
skinparam packageStyle rectangle

package "User 集約" {
  object User {
    +ユーザーID
    +名前
    +メールアドレス
    +パスワード
    +プロフィールID
  }

  object Profile {
    +プロフィールID
    +ユーザーID
    +自己紹介
    +顔写真
  }

  User "1" -- "1" Profile

  note left of User
    ユーザーID: UUID
    名前: 1文字以上50文字以内
    メールアドレス: メールアドレス形式
    パスワード: 8文字以上英数字のみ、100文字以内
    かつ英数字それぞれ1文字以上
  end note

  note left of Profile
    自己紹介: 1000文字以内
    顔写真: 1枚のみ
  end note
}

package "Like 集約" {
  object Like {
    +いいねID
    +送信者ユーザーID
    +受信者ユーザーID
    +作成日時
  }

  note left of Like
    - 1人のユーザーに
    １度しかいいねできない
    - 送信者と受信者は異なる
    - 1ヶ月に100回までしかいいねできない
  end note
}

package "Match 集約" {
  object Match {
    +マッチID
    +ユーザーID1
    +ユーザーID2
    +作成日時
  }

  note right of Match
    - お互いにいいねしたらマッチ成立
  end note
}

package "Talk 集約" {
  object Message {
    +メッセージID
    +送信者ユーザーID
    +受信者ユーザーID
    +メッセージ内容
    +送信日時
  }

  object Talk {
    +会話ID
    +マッチID
    +最終メッセージ日時
    +メッセージ数
  }

  Talk "1" -- "*" Message

  note right of Message
    - 送信者と受信者は異なる
    - メッセージ内容は1文字以上1000文字以内
    - メッセージは１回送ったら削除・編集不可
  end note

  note right of Talk
    - Matchごとに1つのTalkが存在
    - メッセージ送信時にメッセージ数を更新
    - 片方がもう片方のユーザーをブロックしたらTalkが削除される
  end note
}

User "1" --> "*" Like : いいね送信
User "1" --> "*" Match : マッチ成立

Message ..> Match : マッチIDで参照
Talk ..> Match : マッチIDで参照
@enduml